# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GalleryDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GalleryDemo

  pod 'Alamofire'	
  pod 'SDWebImage'
  pod 'MJRefresh'

  target 'GalleryDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GalleryDemoUITests' do
    # Pods for testing
  end

end
